# version: "3.8"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

volumes:
  finara:
# docker compose up --build - using docker compose
# docker compose watch - to watch for changes
